version: '3'
services:

    nginx:
        container_name: nginx
        build: ./KHU_Seraph_nginx
        image: jaeholeekr/nginx
        restart: always
        ports:
          - "30080:80"
        volumes:
          - ./KHU_Seraph_django:/srv/docker-server
          - ./log:/var/log/nginx
        depends_on:
          - django

    django:
        container_name: django
        build: ./KHU_Seraph_django
        image: jaeholeekr/django
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./KHU_Seraph_django:/srv/docker-server
          - ./log:/var/log/uwsgi